# conda env create -n rise -f environment.yml
# conda env update --file environment.yml  --prune
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pandas
  - sympy=1.8
  - sklearn-pandas
  - bokeh
  - rise
  - pip
  - pip:
    - jupyter-contrib-nbextensions
    - hide_code
