# mamba env create -n rise -f environment.yml
# mamba env update -n rise -f environment.yml  --prune
channels:
  - conda-forge
dependencies:
  - conda
  - mamba
  - python
  - numpy
  - scipy
  - sage
  - matplotlib
  - pandas
  - sympy=1.8
  - sklearn-pandas
  - bokeh
  - jinja2=3.0.3
  - openssl
  - rise
  - pip
  - pip:
    - jupyter-contrib-nbextensions
    - hide-code
    - jupytext==1.14.4
    - ipywidgets